#include "/Engine/Public/Platform.ush"

Texture2D<float> InputDepthMap;
SamplerState InputDepthMapSampler;
RWStructuredBuffer<float> OutputBuffer;


[numthreads(128, 1, 1)]
void Main(uint ThreadId : SV_DispatchThreadID)
{
    if (ThreadId >= 1024) return;

    float2 uv = float2(0.5f, 0.5f);
    float value = InputDepthMap.SampleLevel(InputDepthMapSampler, uv, 0);
    OutputBuffer[ThreadId] = value;
}